### ISSUE TITLE
Описание работ

### ISSUE THREAD

**Issue by kruglovaliza** [kruglovaliza/TRPO-LR--5#10]
Кратко расписать, как выполняли задания, добавить к описанию скриншоты ключевых моментов

**Comment by katemless** [comment]
Превью:
![1](https://user-images.githubusercontent.com/61832624/79743812-ec454e80-830d-11ea-957f-ed650631be96.png)
_Вырезание элемента_
![Cinema](https://user-images.githubusercontent.com/61832624/79743922-26165500-830e-11ea-9fe4-156810dc524f.png)
_Создание надписи в Cinema 4D_
![6](https://user-images.githubusercontent.com/61832624/79743957-375f6180-830e-11ea-9948-ed39cac4868e.png)
_Добавление надписи, текстур и немного цветокоррекции_
![8](https://user-images.githubusercontent.com/61832624/79744057-61b11f00-830e-11ea-80cb-6ea51d1c0d48.png)
_Добавление еще текстур и прочих элементов_

**Comment by katemless** [comment]
Заставка:
![3](https://user-images.githubusercontent.com/61832624/79744508-1ea37b80-830f-11ea-995b-ca2c63521df4.png)
_Вырезание части объекта_
![4](https://user-images.githubusercontent.com/61832624/79744530-2a8f3d80-830f-11ea-9880-7227fcfb5cfd.png)
_Добавление надписи и создание однородности фона_
![9](https://user-images.githubusercontent.com/61832624/79744577-42ff5800-830f-11ea-8d26-f72d075ea0c4.png)
_Рисование пиксельной иллюстрации в духе старых аркадных игр_
![5](https://user-images.githubusercontent.com/61832624/79744689-7c37c800-830f-11ea-90f5-3632d9d420a7.png)
_Добавление всех элементов_

**Comment by Mildonir** [comment]
История создания игры: 
![image](https://user-images.githubusercontent.com/61844936/79745198-6d054a00-8310-11ea-88af-7505fca06c77.png)

**Comment by kruglovaliza** [comment]
1. Работа в приложении Streamlabs OBS:
![image](https://user-images.githubusercontent.com/61828720/79804040-dc5c5780-836b-11ea-9137-b491f258a138.png)
2. Работа над презентацией в PowerPoint:
![image](https://user-images.githubusercontent.com/61828720/79804128-0d3c8c80-836c-11ea-8b73-210f2b466519.png)
