### ISSUE TITLE
Указание ссылок

### ISSUE THREAD

**Issue by kruglovaliza** [kruglovaliza/TRPO-LR--5#11]
Составить список всех используемых материалов с ссылками на то, откуда они взяты

**Comment by katemless** [comment]
Гифки: https://giphy.com/
Изображение, использованное для превью: https://www.1000bit.it/support/articoli/spacewar.png
Изображение, использованное для заставки: https://avatars.mds.yandex.net/get-zen_doc/1210285/pub_5b4f9b76e83ed200aa463cde_5b53ddb57438af00a9921681/scale_1200

**Comment by Mildonir** [comment]
Музыка взята с сайта YouTube (https://www.youtube.com/watch?v=5qap5aO4i9A).
Информация о истории создания первой игры: https://i-fakt.ru/pervaya-kompyuternaya-igra-v-mire/  http://www.gamer.ru/everything/spacewar-pervaya-kompyuternaya-igra-v-istorii-ekskursiya-v-proshloe

**Comment by kruglovaliza** [comment]
Ссылки на изображения, используемые в презентации проекта:
1. https://upload.wikimedia.org/wikipedia/commons/2/23/Spacewar%21-PDP-1-20070512.jpg
2. https://thumbs.gfycat.com/AppropriateImmaterialCockatoo-size_restricted.gif
3. https://d284x0ytlho6sy.cloudfront.net/images/blog-images/game-to-play-online/spacewar.jpg
4. https://stopga.me/images/blogs/2018/09/05/usdzAj-s4.jpg
5. https://i.pinimg.com/originals/8e/2f/d7/8e2fd74b360e863b44cedfc2bbc65718.jpg
6. https://i.ytimg.com/vi/yY5qHe2VadA/hqdefault.jpg
7. https://cdn.mos.cms.futurecdn.net/f8c334c94b519280eb731295d3d3319e.jpg
8. https://erealityhome.files.wordpress.com/2007/12/ttt_play2.gif
9. https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Pong_Game_Test2.gif/220px-Pong_Game_Test2.gif
10. https://i.redd.it/ecx45t2f29py.jpg
