### ISSUE TITLE
Поиск изображений для элементов

### ISSUE THREAD

**Issue by kruglovaliza** [kruglovaliza/TRPO-LR--5#13]
Найти (или создать) изображения для элементов "подпишись" и "поставь лайк"

**Comment by katemless** [comment]
![Подпишись](https://user-images.githubusercontent.com/61832624/79749507-03893980-8318-11ea-94ff-64a65ac0dfa6.png)
![like](https://user-images.githubusercontent.com/61832624/79749517-06842a00-8318-11ea-8d5e-28ffbfccb2be.png)

**Comment by katemless** [comment]
![Подпишись](https://user-images.githubusercontent.com/61832624/79749788-785c7380-8318-11ea-8c7a-3fc17a5132ff.png)
![like](https://user-images.githubusercontent.com/61832624/79749790-798da080-8318-11ea-9247-e122e12f3c92.png)

**Comment by katemless** [comment]
![like2](https://user-images.githubusercontent.com/61832624/79775276-ace22680-833c-11ea-9deb-694830770098.png)
