### ISSUE TITLE
Оформление заставки и превью

### ISSUE THREAD

**Issue by kruglovaliza** [kruglovaliza/TRPO-LR--5#2]
Оформить заставку и превью для стрима, подходящие под тему проекта

**Comment by katemless** [comment]
![preview](https://user-images.githubusercontent.com/61832624/79736555-a3d46380-8302-11ea-86fa-5b3fe5ab5467.png)
![заставка](https://user-images.githubusercontent.com/61832624/79736563-a767ea80-8302-11ea-9960-57c5a8eb4988.png)
