### ISSUE TITLE
Поиск гифок

### ISSUE THREAD

**Issue by kruglovaliza** [kruglovaliza/TRPO-LR--5#5]
Найти подходящие гифки для ключевых моментов, не меньше 3х

**Comment by katemless** [comment]
![giphy (5)](https://user-images.githubusercontent.com/61832624/79736642-d0887b00-8302-11ea-8231-918351effeb0.gif)
![giphy](https://user-images.githubusercontent.com/61832624/79736668-d8e0b600-8302-11ea-9d73-b4842b29d5d2.gif)
![giphy (8)](https://user-images.githubusercontent.com/61832624/79736698-e26a1e00-8302-11ea-87f9-8a42c83f8ffc.gif)
![giphy (9)](https://user-images.githubusercontent.com/61832624/79736709-e85fff00-8302-11ea-80df-664280739901.gif)
![giphy (3)](https://user-images.githubusercontent.com/61832624/79736719-ed24b300-8302-11ea-93e1-5f814a8746f7.gif)
